### ISSUE TITLE
Tor Relay Activity - Microsoft Defender Advanced Hunting Query

### ISSUE THREAD

**Issue by SunsetPlague** [Dylan-J/Tor-Project-Statistics#4]
Hello,

I have this query running as a detection rule but a little while ago I noticed it started to fail and stopped working.
When trying to access the website with the Tor Relay IP's, etc. I get an error. So I'm not sure if the websites have moved but haven't been updated or if it's related to the query itself.

Please advise?

Thank you!

**Comment by Dylan-J** [comment]
Thanks for pointing that out mate! I published the update to the Microsoft GitHub repo and not my source repo here (*facepalm*). I have updated the query in the master branch, for reference the URL you will want to change in your detection rule is:

```
https://torinfo.blob.core.windows.net/public/TorRelayIPs.csv
```
